name: "Publish to flakestry.dev"
on:
  push:
    branches:
      - main

jobs:
  flakestry-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          fetch-tags: true
      - name: Retrieve commit count
        run: echo "COMMITS=$(git rev-list --count main)" >> $GITHUB_ENV
      - uses: flakestry/flakestry-publish@main
        with:
          version: "v0.1.${{ env.COMMITS }}"
